VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Define the base box
    config.vm.box = "ubuntu/bionic64"

    # Create a master node
    config.vm.define "k8s-master" do |master|
        master.vm.hostname = "k8s-master"
        master.vm.network "private_network", ip: "192.168.56.10"
        master.vm.provision "shell", path: "kubernetes-setup.sh", args: ["master"]
    end

    # Create worker nodes
    (1..2).each do |i|
        config.vm.define "k8s-worker#{i}" do |worker|
            worker.vm.hostname = "k8s-worker#{i}"
            worker.vm.network "private_network", ip: "192.168.56.1#{i}"
            worker.vm.provision "shell", path: "kubernetes-setup.sh", args: ["worker0#{i}"]
        end
    end

    # Customize the amount of memory on the VM
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
    end
end
