---
- hosts: all
  become: true

  tasks:
    - name: Create a non-root user named kuberunner
      user:
        name: kuberunner
        state: present
        shell: /bin/bash

    - name: Set sudoers for kuberunner
      copy:
        dest: /etc/sudoers.d/kuberunner
        content: |
          kuberunner ALL=(ALL) NOPASSWD:ALL
      mode: '0440'

    - name: Add local machine's public key to kuberunner's authorized_keys
      authorized_key:
        user: kuberunner
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
